// Generated by https://quicktype.io

export interface Error {
  status:     number;
  statusText: string;
  internal:   boolean;
  data:       string;
  error:      ErrorClass;
}

export interface ErrorClass {
}
